import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { EventEmitter } from 'node:events';
import {
  createVercelConfig,
  createNetlifyConfig,
  createDeployPackageJson,
  deploy,
} from '../../src/cli/commands/deploy.js';
import {
  createTestProjectDir,
  createMockSupaslidevWorkspace,
  createMockSlidevProject,
  cleanupTestDir,
} from '../helpers/import-test-helpers.js';

vi.mock('../../src/cli/utils.js', () => ({
  findProjectRoot: vi.fn(),
  getPresentations: vi.fn(() => []),
}));

vi.mock('../../src/shared/presentations.js', () => ({
  regeneratePresentationsJson: vi.fn(),
}));

const createMockChildProcess = () => {
  const emitter = new EventEmitter();
  return emitter as EventEmitter & { emit: (event: string, ...args: unknown[]) => boolean };
};

vi.mock('node:child_process', () => ({
  spawn: vi.fn(() => createMockChildProcess()),
}));

vi.spyOn(console, 'log').mockImplementation(() => {});
vi.spyOn(console, 'error').mockImplementation(() => {});
vi.spyOn(console, 'warn').mockImplementation(() => {});

describe('createVercelConfig', () => {
  it('generates rewrites for each presentation plus catch-all', () => {
    const config = JSON.parse(createVercelConfig('/', ['deck-a', 'deck-b']));

    expect(config.rewrites).toHaveLength(3);
    expect(config.rewrites[0]).toEqual({
      source: '/presentations/deck-a/:path((?!.*\\.).*)',
      destination: '/presentations/deck-a/index.html',
    });
    expect(config.rewrites[1]).toEqual({
      source: '/presentations/deck-b/:path((?!.*\\.).*)',
      destination: '/presentations/deck-b/index.html',
    });
    expect(config.rewrites[2]).toEqual({
      source: '/:path((?!.*\\.).*)',
      destination: '/index.html',
    });
  });

  it('applies custom base path', () => {
    const config = JSON.parse(createVercelConfig('/my-site/', ['demo']));

    expect(config.rewrites[0].source).toBe('/my-site/presentations/demo/:path((?!.*\\.).*)');
    expect(config.rewrites[1].source).toBe('/my-site/:path((?!.*\\.).*)');
  });

  it('handles empty presentations array', () => {
    const config = JSON.parse(createVercelConfig('/', []));

    expect(config.rewrites).toHaveLength(1);
    expect(config.rewrites[0].source).toBe('/:path((?!.*\\.).*)');
  });
});

describe('createNetlifyConfig', () => {
  it('generates redirects for each presentation plus catch-all', () => {
    const config = createNetlifyConfig('/', ['deck-a', 'deck-b']);

    expect(config).toContain('from = "/presentations/deck-a/*"');
    expect(config).toContain('to = "/presentations/deck-a/index.html"');
    expect(config).toContain('from = "/presentations/deck-b/*"');
    expect(config).toContain('to = "/presentations/deck-b/index.html"');
    expect(config).toContain('from = "/*"');
    expect(config).toContain('to = "/index.html"');
    expect(config).toContain('status = 200');
  });

  it('applies custom base path', () => {
    const config = createNetlifyConfig('/my-site/', ['demo']);

    expect(config).toContain('from = "/my-site/presentations/demo/*"');
    expect(config).toContain('from = "/my-site/*"');
  });

  it('includes auto-generated header', () => {
    const config = createNetlifyConfig('/', []);

    expect(config).toContain('# Auto-generated by supaslidev deploy');
  });
});

describe('createDeployPackageJson', () => {
  it('generates valid package.json with serve script', () => {
    const pkg = JSON.parse(createDeployPackageJson());

    expect(pkg.name).toBe('supaslidev-deploy');
    expect(pkg.private).toBe(true);
    expect(pkg.scripts.start).toBe('npx serve .');
  });
});

describe('deploy', () => {
  let testDir: string;

  beforeEach(() => {
    testDir = createTestProjectDir('deploy');
    vi.clearAllMocks();
  });

  afterEach(() => {
    cleanupTestDir(testDir);
  });

  it('throws when no project root is found', async () => {
    const { findProjectRoot } = await import('../../src/cli/utils.js');
    vi.mocked(findProjectRoot).mockReturnValue(null);

    await expect(deploy()).rejects.toThrow('Could not find a Supaslidev project');
  });

  it('throws when no presentations exist', async () => {
    const { findProjectRoot, getPresentations } = await import('../../src/cli/utils.js');
    const workspaceDir = join(testDir, 'workspace');
    createMockSupaslidevWorkspace(workspaceDir);
    vi.mocked(findProjectRoot).mockReturnValue(workspaceDir);
    vi.mocked(getPresentations).mockReturnValue([]);

    await expect(deploy()).rejects.toThrow('No presentations found');
  });

  it('throws when output directory is outside project root', async () => {
    const { findProjectRoot, getPresentations } = await import('../../src/cli/utils.js');
    const workspaceDir = join(testDir, 'workspace');
    createMockSupaslidevWorkspace(workspaceDir);
    mkdirSync(join(workspaceDir, 'presentations', 'demo'), { recursive: true });
    writeFileSync(join(workspaceDir, 'presentations', 'demo', 'slides.md'), '# Demo');
    vi.mocked(findProjectRoot).mockReturnValue(workspaceDir);
    vi.mocked(getPresentations).mockReturnValue(['demo']);

    await expect(deploy({ output: '/tmp/somewhere-else' })).rejects.toThrow(
      'outside the project root',
    );
  });

  it('passes validation and invokes slidev build for output within project root', async () => {
    const { findProjectRoot, getPresentations } = await import('../../src/cli/utils.js');
    const { spawn } = await import('node:child_process');
    const workspaceDir = join(testDir, 'workspace');
    createMockSupaslidevWorkspace(workspaceDir);
    vi.mocked(findProjectRoot).mockReturnValue(workspaceDir);
    vi.mocked(getPresentations).mockReturnValue(['demo']);

    // Make slidev build succeed, then make nuxt generate fail
    vi.mocked(spawn).mockImplementation(() => {
      const child = createMockChildProcess();
      setImmediate(() => child.emit('close', 1));
      return child as ReturnType<typeof spawn>;
    });

    const outputDir = join(workspaceDir, 'deploy');

    // Deploy passes the output-path safety check but fails at slidev build (exit code 1)
    await expect(deploy({ output: outputDir })).rejects.toThrow('exited with code 1');

    // Verify slidev build was called with correct base path
    expect(spawn).toHaveBeenCalledWith(
      'npx',
      ['slidev', 'build', '--base', '/presentations/demo/'],
      expect.objectContaining({ stdio: 'inherit' }),
    );
  });
});
