packages:
  - 'packages/*'
  - 'playground'
  - 'playground/presentations/*'
  - 'docs'

catalog:
  '@slidev/cli': ^52.11.3
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  vue: ^3.5.26
  '@vue/compiler-sfc': ^3.5.27
  typescript: ^5.3.3
  vue-tsc: ^2.0.0
