packages:
  - packages/*
  - playground
  - playground/packages/*
  - playground/presentations/*
  - docs

catalog:
  '@slidev/cli': ^52.14.1
  '@slidev/theme-apple-basic': latest
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  knip: ^6.2.0
  playwright-chromium: ^1.59.1
  vue: ^3.5.31

catalogMode: prefer

catalogs:
  cli:
    '@clack/prompts': ^1.2.0
    commander: ^14.0.3
    ejs: ^5.0.0
    js-yaml: ^4.1.1
    picocolors: ^1.1.1
    ts-morph: ^28.0.0
    yaml: ^2.8.3
  core:
    '@nuxt/devtools-kit': ^4.0.0-alpha.3
    '@nuxt/kit': ^4.4.2
    '@nuxt/schema': ^4.4.2
    '@nuxt/ui': ^4.6.0
    '@vitejs/plugin-vue': ^6.0.5
    '@vue/compiler-sfc': ^3.5.31
    better-sqlite3: ^12.8.0
    docus: ^5.8.1
    mermaid: ^11.14.0
    nuxt: ^4.4.2
    tailwindcss: ^4.2.2
    vite: ^8.0.3
    vue-router: ^5.0.4
    vue-tsc: ^3.2.6
    zod: ^4.3.6
    zod-to-json-schema: ^3.25.2
  dev:
    '@commitlint/cli': ^20.5.0
    '@commitlint/config-conventional': ^20.5.0
    '@types/ejs': ^3.1.5
    '@types/js-yaml': ^4.0.9
    '@types/node': ^24.12.0
    '@vitest/browser': 4.1.2
    '@vitest/browser-playwright': 4.1.2
    '@vitest/coverage-v8': 4.1.2
    '@vitest/ui': ^4.1.2
    bumpp: ^11.0.1
    changelogen: ^0.6.2
    changelogithub: ^14.0.0
    husky: ^9.1.7
    lint-staged: ^16.4.0
    oxfmt: ^0.43.0
    oxlint: ^1.58.0
    playwright: ^1.59.1
    playwright-chromium: ^1.59.1
    tsdown: ^0.21.7
    tsx: ^4.21.0
    turbo: ^2.9.3
    typescript: ^6.0.0
    vitest: ^4.1.2

ignoredOptionalDependencies:
  - '@resvg/resvg-js-android-arm-eabi'
  - '@resvg/resvg-js-android-arm64'
  - '@resvg/resvg-js-darwin-x64'
  - '@resvg/resvg-js-linux-arm-gnueabihf'
  - '@resvg/resvg-js-linux-arm64-gnu'
  - '@resvg/resvg-js-linux-arm64-musl'
  - '@resvg/resvg-js-linux-x64-gnu'
  - '@resvg/resvg-js-linux-x64-musl'
  - '@resvg/resvg-js-win32-arm64-msvc'
  - '@resvg/resvg-js-win32-ia32-msvc'
  - '@resvg/resvg-js-win32-x64-msvc'

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - playwright-chromium
  - sharp
  - vue-demi

shellEmulator: true

trustPolicy: accept

trustPolicyExclude:
  - axios
  - chokidar
  - semver
  - undici
  - undici-types
  - vite
