import { spawn } from 'node:child_process';
import { join, dirname, resolve } from 'node:path';
import { existsSync, mkdirSync, cpSync, rmSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { findProjectRoot, getPresentations } from '../utils.js';
import { regeneratePresentationsJson } from '../../shared/presentations.js';

export interface DeployOptions {
  output?: string;
  base?: string;
}

function findSupaslidevPackageRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));

  while (dir !== dirname(dir)) {
    const packageJsonPath = join(dir, 'package.json');
    if (existsSync(packageJsonPath)) {
      try {
        const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
        if (pkg.name === 'supaslidev') {
          return dir;
        }
      } catch {
        // Continue searching
      }
    }
    dir = dirname(dir);
  }

  throw new Error('Could not find supaslidev package root');
}

function runCommand(
  command: string,
  args: string[],
  options: { cwd: string; env?: Record<string, string | undefined> },
): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      stdio: 'inherit',
      shell: process.platform === 'win32',
      env: options.env ?? process.env,
    });

    child.on('error', (err) => {
      reject(new Error(`Failed to run ${command}: ${err.message}`));
    });

    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`${command} exited with code ${code}`));
      } else {
        resolve();
      }
    });
  });
}

function findNuxtBin(
  projectRoot: string,
  supaslidevRoot: string,
): { command: string; args: string[] } {
  const projectNuxtBin = join(projectRoot, 'node_modules', '.bin', 'nuxt');
  const packageNuxtBin = join(supaslidevRoot, 'node_modules', '.bin', 'nuxt');

  if (existsSync(projectNuxtBin)) {
    return { command: projectNuxtBin, args: [] };
  } else if (existsSync(packageNuxtBin)) {
    return { command: packageNuxtBin, args: [] };
  }
  return { command: 'npx', args: ['nuxt'] };
}

export function createVercelConfig(basePath: string, presentations: string[]): string {
  const rewrites = presentations.map((id) => ({
    source: `${basePath}presentations/${id}/(.*)`,
    destination: `${basePath}presentations/${id}/index.html`,
  }));

  rewrites.push({
    source: `${basePath}(.*)`,
    destination: `${basePath}index.html`,
  });

  return JSON.stringify({ rewrites }, null, 2);
}

export function createNetlifyConfig(basePath: string, presentations: string[]): string {
  const lines = ['# Auto-generated by supaslidev deploy', ''];

  for (const id of presentations) {
    lines.push('[[redirects]]');
    lines.push(`  from = "${basePath}presentations/${id}/*"`);
    lines.push(`  to = "${basePath}presentations/${id}/index.html"`);
    lines.push('  status = 200');
    lines.push('');
  }

  lines.push('[[redirects]]');
  lines.push(`  from = "${basePath}*"`);
  lines.push(`  to = "${basePath}index.html"`);
  lines.push('  status = 200');
  lines.push('');

  return lines.join('\n');
}

export function createDeployPackageJson(): string {
  return JSON.stringify(
    {
      name: 'supaslidev-deploy',
      private: true,
      scripts: {
        start: 'npx serve .',
      },
    },
    null,
    2,
  );
}

export async function deploy(options: DeployOptions = {}): Promise<void> {
  const projectRoot = findProjectRoot();

  if (!projectRoot) {
    throw new Error(
      'Could not find a Supaslidev project. Make sure you are in a directory with a "presentations" folder.',
    );
  }

  const presentationsDir = join(projectRoot, 'presentations');
  const presentations = getPresentations(presentationsDir);

  if (presentations.length === 0) {
    throw new Error('No presentations found in the presentations directory.');
  }

  const outputDir = resolve(options.output ?? join(projectRoot, 'deploy'));
  const resolvedProjectRoot = resolve(projectRoot);

  // Safety check: prevent deleting directories outside the project root
  if (!outputDir.startsWith(resolvedProjectRoot)) {
    throw new Error(
      `Output directory "${outputDir}" is outside the project root "${resolvedProjectRoot}". Use a path within your project.`,
    );
  }
  const basePath = (options.base ?? '/').replace(/\/*$/, '/');

  const supaslidevRoot = findSupaslidevPackageRoot();
  const presentationsJsonPath = join(projectRoot, '.supaslidev', 'presentations.json');

  console.log('\n' + '='.repeat(50));
  console.log('  Supaslidev Deploy');
  console.log('='.repeat(50));
  console.log(`\n  Project: ${projectRoot}`);
  console.log(`  Output:  ${outputDir}`);
  console.log(`  Base:    ${basePath}`);
  console.log(`  Presentations: ${presentations.join(', ')}`);
  console.log('');

  // Step 1: Build each presentation with slidev build --base
  console.log(`Step 1/${4}: Building ${presentations.length} presentation(s)...\n`);

  for (const id of presentations) {
    const presentationDir = join(presentationsDir, id);
    const presentationBase = `${basePath}presentations/${id}/`;

    console.log(`  Building: ${id} (base: ${presentationBase})`);

    await runCommand('npx', ['slidev', 'build', '--base', presentationBase], {
      cwd: presentationDir,
    });

    console.log(`  Done: ${id}\n`);
  }

  // Step 2: Generate presentations.json
  console.log('Step 2/4: Generating presentations.json...\n');

  regeneratePresentationsJson(presentationsDir, presentationsJsonPath);

  // Step 3: Build the Nuxt dashboard in static mode
  console.log('Step 3/4: Building dashboard...\n');

  const nuxt = findNuxtBin(projectRoot, supaslidevRoot);

  const nuxtEnv: Record<string, string | undefined> = {
    ...process.env,
    NODE_ENV: 'production',
    SUPASLIDEV_PROJECT_ROOT: projectRoot,
    SUPASLIDEV_PRESENTATIONS_DIR: presentationsDir,
    NUXT_PUBLIC_DEPLOY_MODE: 'true',
  };

  // Strip test runner env vars
  for (const key of Object.keys(nuxtEnv)) {
    if (key === 'VITEST' || key.startsWith('VITEST_') || key === 'TEST') {
      delete nuxtEnv[key];
    }
  }

  await runCommand(nuxt.command, [...nuxt.args, 'generate'], {
    cwd: supaslidevRoot,
    env: nuxtEnv,
  });

  // Step 4: Assemble output directory
  console.log('\nStep 4/4: Assembling deploy output...\n');

  // Clean and create output directory
  if (existsSync(outputDir)) {
    rmSync(outputDir, { recursive: true });
  }
  mkdirSync(outputDir, { recursive: true });

  // Copy Nuxt output — nuxt generate runs in supaslidevRoot so .output lands there
  const nuxtOutputDir = join(supaslidevRoot, '.output', 'public');
  if (existsSync(nuxtOutputDir)) {
    cpSync(nuxtOutputDir, outputDir, { recursive: true });
  } else {
    throw new Error('Nuxt generate did not produce output at .output/public/');
  }

  // Copy each presentation's dist into output/presentations/<id>/
  const presentationsOutputDir = join(outputDir, 'presentations');
  mkdirSync(presentationsOutputDir, { recursive: true });

  for (const id of presentations) {
    const distDir = join(presentationsDir, id, 'dist');
    const destDir = join(presentationsOutputDir, id);

    if (existsSync(distDir)) {
      cpSync(distDir, destDir, { recursive: true });
    } else {
      console.warn(`  Warning: No dist/ found for presentation "${id}", skipping.`);
    }
  }

  // Copy presentations.json to output root
  if (existsSync(presentationsJsonPath)) {
    cpSync(presentationsJsonPath, join(outputDir, 'presentations.json'));
  }

  // Generate platform config files
  writeFileSync(join(outputDir, 'vercel.json'), createVercelConfig(basePath, presentations));
  writeFileSync(join(outputDir, 'netlify.toml'), createNetlifyConfig(basePath, presentations));
  writeFileSync(join(outputDir, 'package.json'), createDeployPackageJson());

  console.log('='.repeat(50));
  console.log('  Deploy package ready!');
  console.log('='.repeat(50));
  console.log(`\n  Output: ${outputDir}/`);
  console.log(`\n  Preview locally:`);
  console.log(`    cd ${outputDir} && npx serve .`);
  console.log(`\n  Deploy with Vercel:`);
  console.log(`    cd ${outputDir} && vercel`);
  console.log(`\n  Deploy with Netlify:`);
  console.log(`    cd ${outputDir} && netlify deploy --prod`);
  console.log(`\n  Or push to Git and import in Vercel/Netlify dashboard.`);
  console.log('');
}
