import { spawn } from 'node:child_process';
import { join, dirname, resolve } from 'node:path';
import {
  existsSync,
  mkdirSync,
  cpSync,
  rmSync,
  writeFileSync,
  readFileSync,
  readdirSync,
  renameSync,
} from 'node:fs';
import { fileURLToPath } from 'node:url';
import { findProjectRoot, getPresentations } from '../utils.js';
import { parseFrontmatter, regeneratePresentationsJson } from '../../shared/presentations.js';
import { optimizeThumbnail } from '../../shared/optimize-thumbnail.js';

export interface DeployOptions {
  output?: string;
  base?: string;
}

function findSupaslidevPackageRoot(): string {
  let dir = dirname(fileURLToPath(import.meta.url));

  while (dir !== dirname(dir)) {
    const packageJsonPath = join(dir, 'package.json');
    if (existsSync(packageJsonPath)) {
      try {
        const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
        if (pkg.name === 'supaslidev') {
          return dir;
        }
      } catch {
        // Continue searching
      }
    }
    dir = dirname(dir);
  }

  throw new Error('Could not find supaslidev package root');
}

function runCommand(
  command: string,
  args: string[],
  options: { cwd: string; env?: Record<string, string | undefined> },
): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      stdio: 'inherit',
      shell: process.platform === 'win32',
      env: options.env ?? process.env,
    });

    child.on('error', (err) => {
      reject(new Error(`Failed to run ${command}: ${err.message}`));
    });

    child.on('close', (code) => {
      if (code !== 0) {
        reject(new Error(`${command} exited with code ${code}`));
      } else {
        resolve();
      }
    });
  });
}

function findNuxtBin(
  projectRoot: string,
  supaslidevRoot: string,
): { command: string; args: string[] } {
  const projectNuxtBin = join(projectRoot, 'node_modules', '.bin', 'nuxt');
  const packageNuxtBin = join(supaslidevRoot, 'node_modules', '.bin', 'nuxt');

  if (existsSync(projectNuxtBin)) {
    return { command: projectNuxtBin, args: [] };
  } else if (existsSync(packageNuxtBin)) {
    return { command: packageNuxtBin, args: [] };
  }
  return { command: 'npx', args: ['nuxt'] };
}

export function createVercelConfig(basePath: string, presentations: string[]): string {
  // Use negative lookahead to exclude paths with a dot (file extensions like .js, .css, .png)
  // so that asset requests are served as static files instead of being rewritten to index.html
  const rewrites = presentations.map((id) => ({
    source: `${basePath}presentations/${id}/:path((?!.*\\.).*)`,
    destination: `${basePath}presentations/${id}/index.html`,
  }));

  rewrites.push({
    source: `${basePath}:path((?!.*\\.).*)`,
    destination: `${basePath}index.html`,
  });

  return JSON.stringify({ rewrites }, null, 2);
}

export function createNetlifyConfig(basePath: string, presentations: string[]): string {
  const lines = ['# Auto-generated by supaslidev deploy', ''];

  for (const id of presentations) {
    lines.push('[[redirects]]');
    lines.push(`  from = "${basePath}presentations/${id}/*"`);
    lines.push(`  to = "${basePath}presentations/${id}/index.html"`);
    lines.push('  status = 200');
    lines.push('');
  }

  lines.push('[[redirects]]');
  lines.push(`  from = "${basePath}*"`);
  lines.push(`  to = "${basePath}index.html"`);
  lines.push('  status = 200');
  lines.push('');

  return lines.join('\n');
}

export function createDeployPackageJson(): string {
  return JSON.stringify(
    {
      name: 'supaslidev-deploy',
      private: true,
      scripts: {
        start: 'npx serve .',
      },
    },
    null,
    2,
  );
}

export async function deploy(options: DeployOptions = {}): Promise<void> {
  const projectRoot = findProjectRoot();

  if (!projectRoot) {
    throw new Error(
      'Could not find a Supaslidev project. Make sure you are in a directory with a "presentations" folder.',
    );
  }

  const presentationsDir = join(projectRoot, 'presentations');
  const presentations = getPresentations(presentationsDir);

  if (presentations.length === 0) {
    throw new Error('No presentations found in the presentations directory.');
  }

  const outputDir = resolve(projectRoot, options.output ?? 'deploy');
  const resolvedProjectRoot = resolve(projectRoot);

  // Safety check: prevent deleting directories outside the project root
  if (!outputDir.startsWith(resolvedProjectRoot)) {
    throw new Error(
      `Output directory "${outputDir}" is outside the project root "${resolvedProjectRoot}". Use a path within your project.`,
    );
  }
  const basePath = (options.base ?? '/').replace(/\/*$/, '/');

  const supaslidevRoot = findSupaslidevPackageRoot();
  const presentationsJsonPath = join(projectRoot, '.supaslidev', 'presentations.json');

  console.log('\n' + '='.repeat(50));
  console.log('  Supaslidev Deploy');
  console.log('='.repeat(50));
  console.log(`\n  Project: ${projectRoot}`);
  console.log(`  Output:  ${outputDir}`);
  console.log(`  Base:    ${basePath}`);
  console.log(`  Presentations: ${presentations.join(', ')}`);
  console.log('');

  const totalSteps = 5;
  const thumbnailsDir = join(projectRoot, 'thumbnails');

  // Step 1: Build each presentation with slidev build --base
  console.log(`Step 1/${totalSteps}: Building ${presentations.length} presentation(s)...\n`);

  for (const id of presentations) {
    const presentationDir = join(presentationsDir, id);
    const presentationBase = `${basePath}presentations/${id}/`;

    console.log(`  Building: ${id} (base: ${presentationBase})`);

    await runCommand('npx', ['slidev', 'build', '--base', presentationBase], {
      cwd: presentationDir,
    });

    console.log(`  Done: ${id}\n`);
  }

  // Step 2: Generate thumbnails for each presentation
  console.log(`Step 2/${totalSteps}: Generating thumbnails...\n`);

  if (!existsSync(thumbnailsDir)) {
    mkdirSync(thumbnailsDir, { recursive: true });
  }

  for (const id of presentations) {
    const presentationDir = join(presentationsDir, id);
    const slidevBin = join(presentationDir, 'node_modules', '.bin', 'slidev');
    const outputBase = join(thumbnailsDir, id);
    const targetFile = join(thumbnailsDir, `${id}.png`);

    // Detect dark mode from frontmatter
    const slidesPath = join(presentationDir, 'slides.md');
    const frontmatter = existsSync(slidesPath)
      ? parseFrontmatter(readFileSync(slidesPath, 'utf-8'))
      : {};
    const useDark = frontmatter.colorSchema === 'dark';

    console.log(`  Thumbnail: ${id}${useDark ? ' (dark mode)' : ''}`);

    const exportArgs = ['export', '--format', 'png', '--range', '1', '--output', outputBase];
    if (useDark) {
      exportArgs.push('--dark');
    }

    try {
      await runCommand(slidevBin, exportArgs, {
        cwd: presentationDir,
      });

      // Slidev exports into a directory <output>/<n>.png — move to <output>.png
      if (!existsSync(targetFile) && existsSync(outputBase)) {
        const pngs = readdirSync(outputBase)
          .filter((f) => f.endsWith('.png'))
          .sort();
        if (pngs.length > 0) {
          renameSync(join(outputBase, pngs[0]), targetFile);
        }
      }

      if (existsSync(targetFile)) {
        await optimizeThumbnail(targetFile);
        console.log(`  Done: ${id}\n`);
      } else {
        console.warn(`  Warning: Thumbnail for "${id}" could not be found after export.\n`);
      }
    } catch {
      console.warn(`  Warning: Thumbnail generation failed for "${id}", skipping.\n`);
    }
  }

  // Step 3: Build the Nuxt dashboard in static mode
  // (runs before presentations.json because the Nitro generate plugin
  // overwrites presentations.json without thumbnail data)
  console.log(`Step 3/${totalSteps}: Building dashboard...\n`);

  const nuxt = findNuxtBin(projectRoot, supaslidevRoot);

  const nuxtEnv: Record<string, string | undefined> = {
    ...process.env,
    NODE_ENV: 'production',
    NITRO_PRESET: process.env.NITRO_PRESET ?? 'static',
    SUPASLIDEV_PROJECT_ROOT: projectRoot,
    SUPASLIDEV_PRESENTATIONS_DIR: presentationsDir,
    NUXT_PUBLIC_DEPLOY_MODE: 'true',
  };

  // Strip test runner env vars
  for (const key of Object.keys(nuxtEnv)) {
    if (key === 'VITEST' || key.startsWith('VITEST_') || key === 'TEST') {
      delete nuxtEnv[key];
    }
  }

  await runCommand(nuxt.command, [...nuxt.args, 'generate'], {
    cwd: supaslidevRoot,
    env: nuxtEnv,
  });

  // Step 4: Generate presentations.json (after Nuxt build so it's not overwritten by Nitro plugin)
  console.log(`\nStep 4/${totalSteps}: Generating presentations.json...\n`);

  regeneratePresentationsJson(presentationsDir, presentationsJsonPath, {
    thumbnailsDir,
    basePath,
  });

  // Step 5: Assemble output directory
  console.log(`\nStep 5/${totalSteps}: Assembling deploy output...\n`);

  // Clean and create output directory
  if (existsSync(outputDir)) {
    rmSync(outputDir, { recursive: true });
  }
  mkdirSync(outputDir, { recursive: true });

  // Copy Nuxt output — nuxt generate runs in supaslidevRoot so .output lands there
  const nuxtOutputDir = join(supaslidevRoot, '.output', 'public');
  if (existsSync(nuxtOutputDir)) {
    cpSync(nuxtOutputDir, outputDir, { recursive: true });
  } else {
    throw new Error('Nuxt generate did not produce output at .output/public/');
  }

  // Copy each presentation's dist into output/presentations/<id>/
  const presentationsOutputDir = join(outputDir, 'presentations');
  mkdirSync(presentationsOutputDir, { recursive: true });

  for (const id of presentations) {
    const distDir = join(presentationsDir, id, 'dist');
    const destDir = join(presentationsOutputDir, id);

    if (existsSync(distDir)) {
      cpSync(distDir, destDir, { recursive: true });
    } else {
      console.warn(`  Warning: No dist/ found for presentation "${id}", skipping.`);
    }
  }

  // Copy thumbnails into output/thumbnails/
  if (existsSync(thumbnailsDir)) {
    const thumbnailsOutputDir = join(outputDir, 'thumbnails');
    mkdirSync(thumbnailsOutputDir, { recursive: true });

    for (const id of presentations) {
      const webpFile = join(thumbnailsDir, `${id}.webp`);
      const pngFile = join(thumbnailsDir, `${id}.png`);
      if (existsSync(webpFile)) {
        cpSync(webpFile, join(thumbnailsOutputDir, `${id}.webp`));
      } else if (existsSync(pngFile)) {
        cpSync(pngFile, join(thumbnailsOutputDir, `${id}.png`));
      }
    }
  }

  // Copy presentations.json to output root
  if (existsSync(presentationsJsonPath)) {
    cpSync(presentationsJsonPath, join(outputDir, 'presentations.json'));
  }

  // Generate platform config files
  writeFileSync(join(outputDir, 'vercel.json'), createVercelConfig(basePath, presentations));
  writeFileSync(join(outputDir, 'netlify.toml'), createNetlifyConfig(basePath, presentations));
  writeFileSync(join(outputDir, 'package.json'), createDeployPackageJson());

  // Generate root vercel.json for build-from-repo workflow if it doesn't exist
  const rootVercelJson = join(projectRoot, 'vercel.json');
  if (!existsSync(rootVercelJson)) {
    const pm = existsSync(join(projectRoot, 'pnpm-lock.yaml'))
      ? 'pnpm'
      : existsSync(join(projectRoot, 'yarn.lock'))
        ? 'yarn'
        : 'npm';
    const vercelConfig = {
      framework: null,
      installCommand: `${pm} install`,
      buildCommand: 'npx supaslidev deploy --output dist',
      outputDirectory: 'dist',
    };
    writeFileSync(rootVercelJson, JSON.stringify(vercelConfig, null, 2) + '\n');
    console.log('  Generated vercel.json in project root for Vercel deployment.\n');
  }

  console.log('='.repeat(50));
  console.log('  Deploy package ready!');
  console.log('='.repeat(50));
  console.log(`\n  Output: ${outputDir}/`);
  console.log(`\n  Preview locally:`);
  console.log(`    cd ${outputDir} && npx serve .`);
  console.log(`\n  Deploy with Vercel:`);
  console.log(`    cd ${outputDir} && vercel`);
  console.log(`\n  Deploy with Netlify:`);
  console.log(`    cd ${outputDir} && netlify deploy --prod`);
  console.log(`\n  Or push to Git and import in Vercel/Netlify dashboard.`);
  console.log('');
}
