packages:
  - 'packages/*'
  - 'presentations/*'

catalog:
  '@slidev/cli': ^52.16.0
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  '@slidev/theme-apple-basic': latest
  vue: ^3.5.35
  playwright-chromium: ^1.60.0

catalogs:
  core:
    nuxt: ^4.4.2
    '@vue/compiler-sfc': ^3.5.35
    typescript: ^6.0.3
    vue-tsc: ^3.3.3

catalogMode: prefer
