packages:
  - 'packages/*'
  - 'presentations/*'

catalog:
  '@slidev/cli': ^52.14.2
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  '@slidev/theme-apple-basic': latest
  vue: ^3.5.32
  playwright-chromium: ^1.59.1

catalogs:
  core:
    nuxt: ^4.4.2
    '@vue/compiler-sfc': ^3.5.32
    typescript: ^6.0.3
    vue-tsc: ^3.2.7

catalogMode: prefer
